### ISSUE TITLE
Schemaless design decision

### ISSUE THREAD

**Issue by tlvenn** [Netflix/falcor#349]
Hi,

I was wondering what has driven the decision to go with a schema less approach ?

By that I mean the client has no idea of relation between entities which creates the need to maintain manually lookup tables and give back to Falcor graph of objects which only use references to handle relations.

It's not so easy to build this kind of graph on the server side as the complexity of your graph grows and it's cumbersome to build and maintain all those lookup tables.

**Comment by raviswc** [comment]
JH - My background is from enterprise applications (internal) that have many teams building services and services exposed to users through flexible front ends that allow configurable views/widgets. For instance, we may have a blotter of Trades and the columns that different sets of users would like to see would be different - this is achieved through user-driven customization/configuration of the UI instead of developer driven custom UIs. Having the ability to introspect what is available from various sources of data is essential to be able to support such usecases - this probably sounds somewhat anti-pattern to the schema-less world of JSON. Another usecase is views that enable users to drill-down/navigate to data from across multiple endpoints/sources seamlessly. Such usecases require the client to be "model/graph-aware". On a related note, with what FALCOR enables, the server-side developers probably become completely agnostic to who is accessing what aspects of data and in which contexts, it would be interesting to understand you may have dealt with breaking changes - from change impact analysis perspective. Also, it is not unusual in our domains to have optimizations applied to certain access patterns either because there are a lot of clients accessing this data or because there is a lot of data for the specific scenario. While some of this goes away with caching, de-dupe etc., it would be very interesting to hear whether your server-side developers have had to do any optimization after their clients switched to falcor.

**Comment by mik01aj** [comment]
Hey guys, You might be interested: I implemented a library which is quite similar to Falcor, but that uses a schema. Here's a comparison: 

# The common part

Both [flying-squirrel](https://github.com/lovelybooks/flying-squirrel) and [Falcor](https://github.com/Netflix/falcor):

* Are data fetching libraries
* Use virtual JSON tree for data modelling
* Help a lot in keeping the APIs consistent
* Have client part and server part
* Handle references efficiently, avoiding roundtrips to server and duplicated data
* Have routing on the server side, with routes doing just one simple thing.
* Support asynchronous route handler results
* Support paths with many ids (Falcor's `PathSet`s)
* Expose just one HTTP endpoint and the result always looks like a part of the big JSON tree.
* Have client-side library that aims to create an illusion that all the data is already there.
* Have one central store to avoid fetching the same data twice
* Support client-side batching (to avoid many HTTP requests)

# The differences

In Falcor, the JSON tree structure can be pretty dynamic: anything in the JSON tree might resolve to a reference (a route handler decides about this). The objects consist of primitive values, and have no guarantees about their types (at least the client code doesn't know the types). This means that Falcor client can work with any Falcor server without much configuration.

In squirrel, all the API structure is defined in a central schema, which is shared between client and server. After you define the schema, the set of routes you have to implement and their return types are fixed. This makes the data structure more rigid, but also more predictable, and this predictability is used heavily by the client part, which produces a structure that mocks the full JSON tree with smart getters that compute parts of the tree lazily and track which nodes in the tree were accessed in order to request the right data afterwards. Thanks to this approach the frontend components can render immediately using the mock data while the real data is fetched in the background.

Squirrel can be used only for fetching the data, not for mutating it (this was planned, but not implemented). Falcor has a nice interface for handling data updates.

Squirrel was created as a side project for data fetching in [LovelyBooks](http://lovelybooks.de) because at this time there was nothing like this available as open source (it was inspired by [the talk introducing GraphQL](https://www.youtube.com/watch?v=9sc8Pyc51uU), but GraphQL itself was not open source at that time). Falcor was open sourced around 3 months after we started using squirrel.

Squirrel will most likely not be mainained anymore, because we're considering switching to Falcor, as it's easier for us to use a library than to maintain our homegrown code.

**Comment by michaelbpaulson** [comment]
Closing as #355 was opened to address this issue.
