### ISSUE TITLE
Rx build with webpack

### ISSUE THREAD

**Issue by michaelbpaulson** [Netflix/falcor#428]
The build with webpack is currently broken with the version of Rx.   The fix was just committed here https://github.com/Reactive-Extensions/RxJS/commit/f078d5648a8f1800e4c54a0ce44df088c306367a

Update and validate that a webpack build works.

**Comment by sdesai** [comment]
Falcor should currently build fine with webpack, given the webpack.config.js checked into Falcor's github master (https://github.com/Netflix/falcor/blob/master/webpack.config.js).

That is, users should be able to clone Falcor, run, for example, `webpack --output-library falcor browser.js falcor.webpack.js` and use `falcor.webpack.js` to work with Falcor.

I just tried it with the falcor-express-demo server, and it's working fine.

I also just validated that it worked with the Rx fix mentioned in the issue, by deleting the webpack.config.js, and pulling in Rx from RxJS#master, as opposed to the npm version, and it also works.

The fix doesn't appear to be on NPM yet though, so we'll need to wait for that.

**Comment by ktrott** [comment]
@michaelbpaulson @sdesai I'm guessing this is no longer an issue?

**Comment by sdesai** [comment]
No longer valid. Core no longer has Rx dependency as of 1.x

**Comment by DrorT** [comment]
@sdesai - why did you choose to take Rx out and recreate the same/similar observable with subscribe?

**Comment by sdesai** [comment]
@DrorT - Being a lower level library, we were aiming to aggressively optimize both run-time and kweight performance, especially along critical/hot paths like `get`, so as to leave enough headroom for app level code to work with.

Since we weren't heavily leveraging Rx that heavily in core, it made sense remove it from core to aggressively tighten up critical paths. However we wanted to provide an Observable interface, so that you could leverage the value of Rx when composing Falcor get/set/call operations alongside other async operations when building apps (where you get considerable value using Rx - simplifying the management and composition of complex app level async operations, e.g: ui interaction -> data retrieval (get) -> rendering -> animation). That's actually why we re-introduce Rx to the stack for all our app code too.

It's win-win really (other than for @michaelbpaulson who has to work without the benefits of Rx in core, but he doesn't mind (too much)).

**Comment by rlueder** [comment]
Hi there,

I seem to be having the issue described in #586, I'm getting the following error when building my react app (I'm using [create-react-app](https://github.com/facebookincubator/create-react-app)):

`./~/rx/dist/rx.aggregates.js`
`Module not found: Can't resolve 'rx' in '/[project_path]/node_modules/rx/dist'`

And here are the Falcor packages I installed:
"falcor": "^0.1.17",
"falcor-http-datasource": "^0.1.3",
"falcor-router": "^0.8.1"

Falcor 0.1.17 still lists rx 2.5.3 in its [dependencies](https://github.com/Netflix/falcor/blob/master/package.json) despite the [comment](https://github.com/Netflix/falcor/issues/428#issuecomment-192440667) from @sdesai?

Am I missing something?

Thanks!
