### ISSUE TITLE
Invalid link to change detection in docs

### ISSUE THREAD

**Issue by petehunt** [Netflix/falcor#441]
There's a link to an unwritten section: http://netflix.github.io/falcor/documentation/model.html#Model-Change-Detection

**Comment by jhusain** [comment]
That's because we're missing change detection at the moment. :-) Will be adding a solution soon. Opening roadmap issue.

**Comment by petehunt** [comment]
@jhusain so if I subscribe to a `get()`, will I see changes pushed through from subsequent `setValue()`s or is that coming soon?

**Comment by jhusain** [comment]
This is one potential approach to change detection which we are exploring (and will almost certainly support). This will likely be exposed as a new method "observe" which has an identical API to get, but returns observables that never end. However we are also exploring a push/pull style of change detection. In this model, we will send a notification that something has changed, and then provide an API which accepts a list of paths and returns only those values that have changed. This push/pull style can be more efficient in certain types of use cases. For example, let's say the application is in a state in which it does not care about the notification. Rather than do the work of marshaling information about which values have changed, we can simply alert to the observer, which can then follow up with a call to retrieve the modified values if the observer deems that necessary. Working on the roadmap for this issue right now.

**Comment by almasakchabayev** [comment]
What is the status of this issue, according to https://github.com/Netflix/falcor/issues/91 observe will not happen?

**Comment by steveorsomethin** [comment]
Closing due to the decision to not implement observe.
