### ISSUE TITLE
number 0 becomes empty atom

### ISSUE THREAD

**Issue by quazzie** [Netflix/falcor#460]
if i ```return [{ path: ['test', 1, 'nr'], value: 0 }]``` from a routers get method the jsonGraph returned has nr as { $type: "atom" } no value.

**Comment by sdesai** [comment]
I believe the fix for this is to change this line:

https://github.com/Netflix/falcor-router/blob/master/src/cache/optimizePathSets.js#L34

To be:

`if (cache === undefined)`

So that we don't inadvertently pick it up as a missing path, and insert the empty atom.

I believe that `undefined` is the only indicator for "no value" (that is, null is valid value, as is 0, "", false etc. which all currently exhibit the same buggy behavior).

Fixes the issue in my local testing, just figuring out what I need to do to test it more broadly (unit tests, integration tests etc.), and will issue a pull request.

**Comment by sdesai** [comment]
Closing this. It's fixed/merged. Forgot to include the issue reference in the commit/PR
