### ISSUE TITLE
Accomadating Large JSON Graphs

### ISSUE THREAD

**Issue by HighOnDrive** [Netflix/falcor#467]
Falcor is something new and I'm left wondering how to best factor my data into a JSON Graph. It would be useful see a sample JSON Graph larger than the TODO example but I don't see it.

Right now my data is curated into multiple JSON document types. Objects/values in several of them are used in combination to define/calculate what the content of the main view will render as. Then there are also multiple resource types which are all curated into their own respective JSON document types.

So, in the end there are about 15 discrete types of JSON document types for the app. Each of these 15 types has myriad variations so that there can be multiple JSON documents under each type. This variation encoding strategy is required to accommodate the the diversity of the industry the app targets. Then at any given time within the app only one of each of the 15 document types is active, meaning that a specific variation in each of the 15 types is being applied to processing or rendering.

I think I'm explaining the situation well enough above. What I want to know is how to best structure this amount and division of data in a Falcor JSON Graph?

A few thoughts and further questions:

• Is the Falcor cache at any given time just the current specific variations that are activated?
• Does each of my document types require a separate JSON graph or even Data Source?
• If it is absolutely required, how do I best jam all that data plus activated ones into one JSON Graph?

**Comment by jhusain** [comment]
It's hard to model your domain with the info above, but I'll try to give you enough information to help you decide if Falcor is appropriate for your problem.

We should separate two things: the data model under the hood, and the data model your application wants to see. JSON Graph is like a SQL view: it is a view  of your backend data designed specifically for your applications needs. Under the circumstances you should structure your JSON Graph to accommodate the way that your application navigates the data.

Have a look at this example of a Router for a Netflix clone. 

https://github.com/netflix/falcor-router-demo

When you enter Netflix, you see a list of genres, each of which contains a list of titles. That's why the root of Netflix's JSON Graph has a genrelists array, each of which contains a genre object, each of which contains a titles array. 

~~~js
{
  genrelist: [
    {
      name: "Horror",
      titles: [
        { $type: "ref", value: ["titlesById", 234] },
        // more title references snipped
      ]
    },
    // more genre lists snipped
  ],
  titlesById: {
    234: {
      "name": "Blitz",
      "year":2011,
      "description":"With a serial killer on the loose...",
      "rating":1.7,
      "boxshot":"http://cdn.test.nflximg.net/images/9236/1919236.jpg",
      "userRating": 5
    },
    // many more titles snipped
  }
}
~~~

In reality, on the backend the data it is spread across multiple data stores. 

Most of the time it's relatively straightforward to take many different JSON documents and integrate them into a single one. It is important that **all of an applications data at the accessible through a single JSON graph resource on the server**. This allows us to retrieve as much or as little data as we want and a single network request.

JSON Graph is ideal for allowing an application to browse data in a Graph gradually. It is optimized for the navigation patterns we see in most connected applications: paging through a list of summarized items, drilling down into one, paging through a list of its child entities, and so on.

If your application mostly browses data, makes minor changes to data locally, and is OK with going to the server to make major changes, Falcor is a pretty good choice. If do you want to run calculations that need access to the entire graph on the client, using JSON Graph it's probably not a good idea. JSON Graph is ideal for gradual navigation, and allowing clients to do useful things without access to all of the data.

**Comment by HighOnDrive** [comment]
Thanks for the clarification. I'm just on a road trip so I'll have a chance to look at the router sample you linked in when I get to my next destination, although I see several obvious things already:

• The JSON Graph is a great way to version an app by limiting app access to specific resources only.
• If this is so I'd like to be able to swap or modify JSON Graphs in such a scenario as users upgrade.
• There will still be resources on the server that will likely not be linked into a JSON Graph.
• There is a need to edit a lot of data, that is the purpose of the app, to be an interactive draw style editor.

Is Falcor a better choice than Firebase in most scenarios?

**Comment by steveorsomethin** [comment]
I'm currently performing issue triage as we get ready to perform a proper release, and closing/tagging as I go.

https://github.com/Netflix/falcor/issues/831 Has some discussion around API versioning. Unfortunately I'm not sure anyone on the team is equipped to answer questions about FireBase.
