### ISSUE TITLE
Can we avoid sentinel cloning when setting JSON Graph into cache?

### ISSUE THREAD

**Issue by jhusain** [Netflix/falcor#48]
Sentinel cloning can't be avoided for PathValues because same object may be reused for several locations in cache. Same is not true of JSON Graph, where same sentinel will always be added to same location.

Should be able to avoid cloning sentinels here because the same sentinel will always be set in the same place. Might improve performance in mainline scenario of loading data from server.

**Comment by michaelbpaulson** [comment]
@jhusain I am going to close this ticket, but give a brief state of the union.

As of now, we _do not_ clone with JSON-Graph, but we should.  If we do not, then the JSON-Graph that is passed in will get severely altered (lots of meta data fields added to it).  Personal opinion here, but an API should avoid mutating input.  Especially since the set JSON-Graph would be unserializable since there are circular references.

But as of now, we do not copy.
