### ISSUE TITLE
Example of use with Angular 1.X

### ISSUE THREAD

**Issue by Bretto** [Netflix/falcor#491]
Whats the best way to use Angular 1.X with Falcor ? Is there some examples around ?

**Comment by rolaveric** [comment]
I've been trying to answer that exact question.
https://github.com/rolaveric/angular-falcor

Still very much a work in progress, but I think I've got something viable using a combination of:
* [`Observable.safeApply()` from rx-angular](https://github.com/Reactive-Extensions/rx.angular.js/) to hook into Angular's $digest loop
* [`Model.getValue]()` from FalcorJS](http://netflix.github.io/falcor/doc/Model.html#getValue) to retrieve our value, returning an observable. And,
* [`Model.getCache()` from FalcorJS](http://netflix.github.io/falcor/doc/Model.html#getCache) to get our value synchronously from the Model's cache.

My latest attempt was to try and use a filter similar to the 'async' pipeline from the Angular2 examples, but I think a better option might be to decorate `falcor.Model` with a new method instead.

I'd be interested to get some feedback on it, especially whether using `Model.getCache()` is right or not.

**Comment by greim** [comment]
Inspired by the above, I've just published this shim library: https://github.com/greim/ng-falcor

**Comment by intellix** [comment]
One thing I didn't understand here is how to simply loop through a set of data. Created a stackoverflow question about it ages ago and nothing was ever said: http://stackoverflow.com/questions/32953976/looping-through-array-of-object-data-within-falcor

When looping through the data, you're also looping through your pathSet keys and the length. I'm guessing you need to do a key check to make sure you're actually looking at data

**Comment by greim** [comment]
I'm not speaking for Netflix/Falcor maintainers, but this is my understanding. If you have a top-level `fooById` entry in your graph, you wouldn't normally loop it. Instead, you'd have an alternate top-level `fooByIndex` entry, keyed by sequential indices, which references into `fooById`.

```js
{
  fooById: {
    19acb34: { ... },
    822ef95: { ... },
    ...
  },
  fooByIndex: {
    0: $ref([ 'fooById', '822ef95' ]),
    1: $ref([ 'fooById', '19acb34' ]),
    ...
  }
}
```

Note: `fooByIndex` might also be named `fooByRecency` or `fooByPopularity` to indicate its ordering. And/or you could have multiple of these for different orderings.

In any case the thing you'd loop would be `fooByIndex`. At that point, one of two things is the case: paging or no paging.

If you're not paging, then you don't need the length anyway; you know where you're starting and ending. So loop on a range like `n = 0..49` and in the body of the loop have paths like `['fooByIndex', n, 'bar']`.

If you're not paging, then presumably you're just displaying all the items in the database. This is kind of a non-Falcorish way of doing things, since loading *everything* is potentially pulling an arbitrarily large chunk of data over the wire. Presumably you'd just determine the maximum number of items you're willing to have in the UI, like say 500 or something. Then, request a range `0..499` and don't bother adding paging logic to the UI (nothing over 500 will appear). Alternatively, request a length, then request the range `0..length`. But this requires two serial requests.

Falcor geniuses correct me if I'm off base here :)

**Comment by steveorsomethin** [comment]
I'm currently performing issue triage as we get ready to perform a proper release, and closing/tagging as I go.

Thanks Greg for the comprehensive answer (+1). In case anyone else arrives here, the only additional color I'll add is that having a summary object describing page sizes/page lengths with serial requests can let you trade some latency for potential performance, as a range of 0-499 could be quite expensive in terms of raw compute both on the client and server (but as always, measure and decide for yourself).

Closing.
