### ISSUE TITLE
`call` caches its result

### ISSUE THREAD

**Issue by dallonf** [Netflix/falcor#494]
I have a `call` endpoint on my server which returns data and/or errors at its own route. (specifically, `model.call('orgs.list.push')` returns `{path: ['orgs', 'list', 'push'], value: {$type: 'atom', value: "Result of the method"}}`)

If I call this method more than once (without explicitly calling `model.invalidate(['orgs', 'list', 'push'])` beforehand), it will simply return the result of the last call. It seems to me like this is incorrect - the point of a `call` is to be a non-idempotent operation, so it shouldn't be making any assumptions about whether its value can be cached.

**Comment by jhusain** [comment]
A call is not supposed to return its result at the path to the function. Calls do not return transient data (ie 2 + 2 === 4). Calls can only modify the JSON Graph on the server and return a subset of the JSON Graph. It seems like you are trying to write a push method. Check out [this example](https://github.com/Netflix/falcor-router-demo/blob/master/index.js#L492). You'll see the functions just adds the item to the list. You can  retrieve the portion of the list you are displaying by passing the thisPaths argument to call.

**Comment by dallonf** [comment]
That makes sense at a high level, but a couple of complications I've found in practice:

1. This is really less of a `push` method and more of a `create` - I'm just kind of cargo-culting from the examples here as I'm trying to make sense of things. The modified length of the list is not as important here as the new item, which has an unknown location in the Graph. Specifically, it's going to be at `orgs.byId[NEW_ID]` - but if I only pass that as a result, the client-side code recieves `{ orgs: byId: { <NEW_ID>: {...} } }`, which means I have to access its data as `json.orgs.byId.<NEW_ID>`... except I don't know what its ID is. 

I suppose could do some crawling through the response with `Object.keys()` to try to determine where the new object lives in the graph, but in my first pass I figured it would be cleaner to respond with something like `{ path: ['orgs', 'list', 'push'], value: { $type: 'ref', value: ['orgs', 'byId', NEW_ID] }` and be able to get a direct reference to the new object. 

2. Where should I put validation errors? If I follow the example and throw them directly, the client only receives `{throwToNext: true}`. I assume this is a bug, and to work around it I started returning `{$type: 'error'}` objects instead - but I need a path for them.

3. There's a lot of cases where I think it does make sense to return arbitrary data from a method like this. A bulk update or delete will often give you a count of how many items were affected, for example - I don't know where a value like this would make sense on the Graph.

**Comment by jhusain** [comment]
Hi @dallonf,

Great questions. There is a simple answer to your first question: how do I retrieve values from a newly added item? As you correctly point out, you have no way of knowing the identifier that will be created for the item that you have added. That's why call offers the **refPaths** argument. This an array of paths which will be looked up on the targets of any references included in the function response. After the function returns a response, the DataSource attempts to retrieve the each of the refPaths from the target of all the references in that response.

Consider the following example:
~~~js
model.call(["orgs.list.push", ["orgname"], 
// refPaths that will be looked up on newly-added org after successful function completion
[
  "name"
],
// thisPaths that will be looked up on list after successful function completion
[
  "length"
]);
~~~

The push function above might return the following response:

~~~js
{
  jsonGraph: {
   orgs: {
    list: {
      7: { $type: "ref", value: ["orgsById, 583] }
    }
   }
  },
  invalidated:[  ["orgs", "length"]  ]
}
~~~

Now the DataSource concatenates the refPaths to the only path within the message at which a reference can be found: ["orgs", "list", 7]. This creates the following path: ["orgs", "list", 7, "name"].

Now the DataSource gets this path and adds it to the message.

~~~js
{
  jsonGraph: {
   orgs: {
    list: {
      7: { $type: "ref", value: ["orgsById, 583] }
    }
   },
   orgsById : {
     583: {
       name: "orgname"
    }
  },
  invalidated:[  ["orgs", "length"]  ]
}
~~~

The same proces is repeated with the thisPaths, except that these paths are retrieved from the fucntion's this object. Finally we get;

~~~js
{
  jsonGraph: {
   orgs: {
    list: {
      7: { $type: "ref", value: ["orgsById, 583] },
      length: 8,
    }
   },
   orgsById : {
     583: {
       name: "orgname"
    }
  },
  invalidated:[  ["orgs", "length"]  ]
}
~~~

As for returning transient data, can you give me some examples where this might be useful? It's not an issue that we have encountered yet, but if we see a legitimate need, we could potentially see adding a mechanism for this.

**Comment by dallonf** [comment]
Ahhhh, that's what `refPaths` does! That makes sense. Although (hate to keep dragging out this issue, just want to fully understand the design here), I wouldn't necessarily want to return a $ref in the response of this call. Imagine I'm trying to wrap a REST API's POST endpoint; all I know is the ID of the newly created object and its attributes. I don't have its location in the newly modified list - or even any guarantee that it was appended at the end of the list - so it doesn't make sense to return `{path: ['orgs', 'list', 7], value: $ref(['orgsById', 583]}` in the response. (I'd rather just invalidate the entire orgs list and have the client re-fetch it the next time it needs it.) 

So I'm still left without a mechanism to query the returned value (unless I could return `{path: ['orgsById', 583], value: $ref(['orgsById', 583]}`, which seems a little... odd)

**Comment by michaelbpaulson** [comment]
@dallonf has this issue been sufficiently answered?  If so, please close.

**Comment by dallonf** [comment]
I'm still unsure whether this was a bug in Falcor or caused by me trying to do something that's unsupported by design, but I'm personally not using Falcor at the moment so I haven't had a chance to test it out on a newer version. I'll go ahead and close it out for now.

**Comment by drFabio** [comment]
Digging this old issue back to the surface

> As for returning transient data, can you give me some examples where this might be useful? It's not an issue that we have encountered yet, but if we see a legitimate need, we could potentially see adding a mechanism for this.

How about validation erros?

**Comment by timkendrick** [comment]
Thanks for the thorough explanation of `refPaths` @jhusain – although as @drFabio asks: how do you model node removal in Falcor?

Example use case: I might want to call an `orgs.list.remove` route, keyed on the *array index* of that item. Once the delete operation succeeds we need to perform various front-end cleanup operations related to the *id* of the item that was removed, etc.

In a traditional REST setup you'd be able to return the ID of the deleted item in the DELETE response body, and the AJAX response handler could trigger cleanup based on this ID. Seeing as the object no longer exists in the graph however, I can't see a way of retrieving the ID of the item that was deleted.

Any suggestions on how to go about this?

**Comment by jhusain** [comment]
If you are removing a node from a list you should already have the ID.  Otherwise how would you avoid race conditions in which the list changes between read and remove operations?

The right approach in Falcor is to create a function which deletes by ID.

Let's say you have the following list:

~~~js 
{
  list: {
    0: {
      $type: “ref”,
      value: [“videosById”, 63973]
    },
   1: {
      $type: “ref”,
      value: [“videosById”, 62873]
    },
  },
  videosById: {
   63973: { name: "House of cards" },
   62873: { name: "Daredevil" }
  }
}
~~~

The first request to retrieve a page of data from the server might look like this:

~~~js 
model.
  get([“list”, 0..10, “name”]).
  then(outputJSONEnvelope => {
    let outputJSON =   outputJSONEnvelope.jsonGraph;
  });
~~~

The output JSON will look like this:

~~~js 
outputJSON = {
  list: {
    0: {
      $path: [“videosById”, 63973],
      name: "House of cards"
    },
   1: {
      $path: [“videosById”, 62873],
      name: "Daredevil"
    },
  }
}
~~~

Now you can call a function you created earlier called "list.remove” which accepts a reference. 

~~~js
model.call ("list.remove", 
[ 
    {
      $type: “ref”,
      value: [“videosById”, 63973]
    }
])
~~~

You can get your hands on the reference pretty easily by using model.deref() on the output JSON.

~~~js 
var listItemModel = model.deref(outputJSON.list[IndexToBeRemoved);
~~~

Internally this model is bound to the reference, and if you JSON.stringify(listItemModel) you get this...

~~~js 
{
  $type: “ref”,
  value: [“videosById”, 63973]
 }
~~~

Therefore you can just write the following code:

~~~js 

var listItemModel = model.deref(outputJSON.list[IndexToBeRemoved);

model.call (
  “list.remove", 
  [ listItemModel ])
~~~

**Comment by timkendrick** [comment]
Thanks for the in-depth response! Perhaps I should have come up with a better example – I was more concerned with the idea of being able to return some transient metadata about an operation (for instance, if a 'delete' call completed with warnings, having some way to access those warnings).

I guess the best way to model this in Falcor would be to have something like a `list.delete.lastResult` route (although I still have to figure out how I'd access this via `refPaths`) – I was just wondering if there were a way I could do this without writing a whole separate route handler purely to cache the last result.

Anyway, thanks again for the help!
