### ISSUE TITLE
Subscribe vs Then

### ISSUE THREAD

**Issue by Bretto** [Netflix/falcor#542]
Whats the difference between the ```subscribe``` and the ```then```. Where should we use one over the over ?

**Comment by trxcllnt** [comment]
Falcor's `ModelResponse` can behave like either an Observable (from Rx) or a Promise (from ES6). If you call `subscribe`, the `ModelResponse` synchronously invokes its cache-search, and will even synchronously notify you of the values (if they're all in the cache locally), before signaling either an error or completion.

Since Promises explicitly define *asynchronous* notification, invoking `then` will never synchronously notify you of information, even if it's in the cache. While this is usually makes little difference to a user in a UI, it can be a detriment in cases like rendering client templates on the server.

**Comment by michaelbpaulson** [comment]
**TL\DR**
Here is a bullet point difference list.
* Promises
  * _not synchronous_ (mentioned above).  A stack frame will be cleared before resolve is called.
  * **Cannot** be used in progressive mode.
  * No cancellation ability
* Subscribe
  * Has completion function
  * Can be onNext'd multiple times
  * **Can** be used in progressive mode.
  * Cancellation is available.

##### long version 

If cancellation and setTimeout is not an issue (performance is not a consideration) then it comes down to progressive mode.  Here is what progressive mode does and how it acts differently in promise vs subscribable mode.

Example:
```

modelAsDataSource = new Model({
    cache: {
        prop: {
            1: 'hello world v1'
        }
    }
}).asDataSource();

model = new Model({
    cache: {
        prop: {
            0: 'hello world'
        }
    },
    source: modelAsDataSource 
})

// makes a request for data
model.get(['prop', {to:1}]).progressively().subscribe(function(x) {
    console.log(JSON.stringify(x, null, 4));
});

// subscribe function is called 2x
// 1st call
{
    json: {
        prop: {
            0: 'hello world'
        }
    }
};

// 2nd call
{
    json: {
        prop: {
            0: 'hello world',
            1: 'hello world v1'
        }
    }
};

// But with a promise this is what it looks like
model.get(['prop', {to:1}]).progressively().then(function(x) {
    console.log(JSON.stringify(x, null, 4));
});

// Output function is called 1 time.  Since we reuse the object we created in the first progressive call you get the same value 2x.
[{
    json: {
        prop: {
            0: 'hello world',
            1: 'hello world v1'
        }
    }
}, {
    json: {
        prop: {
            0: 'hello world',
            1: 'hello world v1'
        }
    }
}];
```

**Comment by michaelbpaulson** [comment]
I closed because I believe that this should be sufficient answers for this question.

**Comment by Bretto** [comment]
Thank you
