### ISSUE TITLE
Falcor Refs Not working

### ISSUE THREAD

**Issue by Chris-Cates** [Netflix/falcor#557]
Hey guys, I have a self contained little app here but I'm confused as to why "greeting" isnt displayed when making a $ref... Please look at the super simple code below:

https://gist.github.com/Chris-Cates/326bc46236fc0720d7e0

**Comment by Chris-Cates** [comment]
I mean Refs and Atoms are the bread and butter of Falcor. So this stuff is important for me!

**Comment by Chris-Cates** [comment]
I just copied and pasted an example from Falcor's API example docs. And it would show up blank
Anyone know why this is happening?

https://gist.github.com/Chris-Cates/a0117954983e5b4fefb2

**Comment by trxcllnt** [comment]
@Chris-Cates I believe you've misunderstood the meaning of `ref` and `atom`.

`Model.ref` is just a convenience method creating Objects with the structure: `{ $type: "ref", value: <your-path> }`, and `Model.atom` is just a convenience method for creating Objects with the structure `{ $type: "atom", value: <your-value> }`.

About your first gist, I'm not sure if I correctly interpreted your intent, but I've tried to capture all the ways you could access "greeting" in this [jsbin](http://jsbin.com/yabayu/edit?html,js,console).

About the second gist, you said you copy/pasted this from the docs? If so, do you mind linking us so we can correct our mistake? [Line 11](https://gist.github.com/Chris-Cates/a0117954983e5b4fefb2#file-wtf-html-L11) should read `["todos", [0,1], ["name","done"]]` instead of `["todos", [12,15], ["name","done"]]`.

Thanks!

**Comment by Chris-Cates** [comment]
@trxcllnt Hey Paul, no I am not confused about refs and atoms. I only had refs in my gists.

Here is the offending code on the Gist.

http://netflix.github.io/falcor/doc/global.html#JSONGraphEnvelope

I tried it with the new code and it works correct.

Thanks for reviewing this!
