### ISSUE TITLE
Issue with set and multi-value paths in falcor router

### ISSUE THREAD

**Issue by nholland94** [Netflix/falcor#576]
Hello. I am experiencing an issue where I try to set the values of multiple paths at once from a Falcor Model, but my route handler only receives a single field with a value (which is always the first alphabetically sorted field).

This is what my Model set call looks like (I have tried it with pathValues as well). In this example, site does not have any fields that are invalid paths.

      return AtreyuModel.set({
        json: {
          peak: {
            site: site
          }
        }
      }).then(function(data) {
        return data.json.peak.site;
      });

And here is the handler for that path.

    var tableFields = [ 'name', 'address', 'optional_address', 'city', 'subregion',  'zip_code' ];

    ....

    {
      route: 'peak.site[' + PathUtils.formatFields(tableFields) + ']',

      get: function(pathSet) {
        var fields = pathSet[2];

        return this.services.peak.site.get().then(function(site) {
          return fields.map(function(field) {
            return {
              path: ['peak', 'site', field],
              value: site[field]
            };
          });
        });
      },

      set: function(jsonGraphArg) {
        console.log(JSON.stringify(arguments));

        return this.services.peak.site.update(jsonGraphArg.peak.site).then(function(site) {
          return tableFields.map(function(field) {
            return {
              path: ['peak', 'site', field],
              value: site[field]
            };
          });
        });
      }
    },

The first console.log statement in the set handler prints out the following: `{"0":{"peak":{"site":{"address":"qwer"}}}}`.

I don't know if this is a bug or just something I'm doing wrong somewhere. I put some debug statements into the falcor router code in my node_modules directory and found out that the root cause is the match function returning a single match with the correct virtual path, but a requested path of ['peak', 'site', 'address'].

**Comment by trxcllnt** [comment]
@nholland94 in your initial `AtreyuModel.set` call, what's the structure of your `site` Object?

**Comment by nholland94** [comment]
@trxcllnt `{"name":"zxcv","address":"qwer","optional_address":null,"city":null,"subregion":"CT","zip_code":null}`

**Comment by trxcllnt** [comment]
@nholland94 I tracked down the source of this issue in falcor-router. For a quick fix, change [this line](https://github.com/Netflix/falcor-router/blob/master/src/operations/matcher/index.js#L155) from
```js
requested: cloneArray(requested),
```
to
```js
requested: path.slice(0, depth),
```
I'm not sure if this is the proper fix, but it fixed the issue you encountered and didn't break any other unit tests.

@michaelbpaulson the matcher ([operations/matcher/index.js](https://github.com/Netflix/falcor-router/blob/master/src/operations/matcher/index.js)) [distributes](https://github.com/Netflix/falcor-router/blob/master/src/operations/matcher/index.js#L43) collapsed PathSets into distinct (simple) matches, but when all the matches [collapse back](https://github.com/Netflix/falcor-router/blob/master/src/operations/matcher/index.js#L75) into a single PathSet, only the [first match](https://github.com/Netflix/falcor-router/blob/master/src/operations/matcher/index.js#L93) is pushed into the `collapsedMatched` list. The `reducedMatch` list has a match for each leaf in the original PathSet, but `collapsedResults` only has one element, since all the matches came from the same PathSet and can be re-collapsed into one Path.

I reproduced this with the following code in node:
```js
var falcor = require("falcor");
var Router = require("falcor-router");
var inspect = require("util").inspect;

falcor({source: new Router([{
    route: ['path', 'to', ['a', 'b', 'c']],
    set: function(jsonGraph) {
        console.log('set route args:', inspect(arguments, {depth: null}));
        return {
            paths: [['path', 'to', ['a', 'b', 'c']]],
            jsonGraph: jsonGraph
        };
    }
}])}).set({json: { path: { to: {
    a: "aaa",
    b: "bbb",
    c: "ccc",
}}}}).subscribe(function(data) {
    console.log('result:', inspect(data, {depth: null}));
});
```

**Comment by nholland94** [comment]
Thanks! That fixed my issue for now.
