### ISSUE TITLE
Model get is resolving as undefined

### ISSUE THREAD

**Issue by dijs** [Netflix/falcor#583]
Very odd issue here.

I am asking for a GET route e.g. `model.get('user.things.name')`

I know this is working on the server side because I see the correct response in my developer tools.

Although, the `GetResponse` promise keeps resolving as `undefined`

Any ideas?

**Comment by trxcllnt** [comment]
@dijs can you post the response you see coming back from the server?

**Comment by dijs** [comment]
Sure.

`{"jsonGraph":{"novels":{"rh":{"title":"Robin Hood Mock"},"wp":{"title":"Winnie the Pooh Mock"}},"user":{"novels":{"title":{"$type":"atom"}}}}}`

**Comment by trxcllnt** [comment]
@dijs aye, the problem is `user.novels.title` an empty `atom`. Essentially, the server is telling the client, "the value you requested doesn't exist, but take this empty placeholder value so next time you don't have to round-trip with me to figure out it doesn't exist again."

This is commonly caused by a route that returns a `PathValue` with an `undefined` as its `value`. If you intend to signal `null`, your route can return a `PathValue` with `null` explicitly. Alternatively, there's an undocumented mode on `falcor.Model` you can trigger (by calling `_materialize()`) that will emit all values, including `undefined` atoms.

**Comment by dijs** [comment]
Forgive me, I am very new to falcor.

I tried returning the model with the materialize, but I am still getting undefined.
```
import {Model} from 'falcor'
import HttpDataSource from 'falcor-http-datasource'
const model = new Model({
	source: new HttpDataSource('/model.json')
})
export default model._materialize()
```

Is there something more I must do? Do I need to tweak the paths at all?

**Comment by trxcllnt** [comment]
@dijs instead of `then` receiving `undefined`, `materialized` mode should send you `{ json: { user: { novels: { title: undefined } } } }` (assuming that's the path you're requesting), but I'll need more info to fully diagnose what's going on.

Can you post the `get` call (including paths) that's not working, and the server-side route that's handling it? Thanks.

**Comment by dijs** [comment]
Server Side:
```es6
{
	route: 'novels.title',
	get: () => {
		let results = []
		const ids = Object.keys(novelsById)
		for (let id of ids) {
			const novel = novelsById[id]
			results.push({
				path: ['novels', id, 'title'],
				value: novel.title
			})
		}
		results.push({
			path: ['novels', 'length'],
			value: ids.length
		})
		return results
	}
}
```

**Comment by trxcllnt** [comment]
@dijs If I understand correctly, the client is doing: `model.get('novels.title')`, right? If so, your route ultimately needs to return a value for the `novels.title` path.

A common pattern when dealing with lists is to define a route for the `length`, then define a route for `{integers}` in that list. So your call patterns and route would look more like this:

```es6
// client
model
  .getValue(['novels', 'length'])
  .then((length) => model.get(['novels', {length}, 'title']))
  .then(({json: { novels }}) => {
    for (var novelIndex in novels) {
      console.log(novelIndex, novels[novelIndex]);
    }
  });
```
```es6
// server
const falcor = require('falcor');
const $ref = falcor.ref;
const $atom = falcor.atom;
const $pathValue = falcor.pathValue;

new Router([{
  route: 'novels.length',
  get: () => {
    return [{
      path: ['novels', 'length'],
      value: Object.keys(novelsById).length
    }];
  }
}, {
  route: 'novels[{integers:novelIndexes}].title',
  get: ({ novelIndexes }) => {
    const results = [];
    const novelIDs = Object.keys(novelsById);
    return novelIndexes.reduce((results, novelIndex) => {
      const novelID = novelIDs[novelIndex];
      const novel = novelsById[novelID];
      // create a reference from 'novels[novelIndex]' to 'novelsById[novelId]'
      results.push($pathValue(
        `novels[${novelIndex}]`,
        $ref(`novelsById['${novelId}']`)
      ));
      // write the novel's actual title to 'novelsById[novelId].title'
      results.push($pathValue(
        `novelsById['${novelId}'].title`,
        $atom(novel.title)
      ));
      return results;
    }, []);
  }
}]);
```

**Comment by dijs** [comment]
Wow, this is intense. I think I understand though. I will have to request a finite numbers of novels first, then I can receive the novels with their ID's. 

Does that sound correct?

Thank you so much for your help by the way!

**Comment by trxcllnt** [comment]
@dijs yes, that's the idea. and no problem, let me know if you have any more questions!
