### ISSUE TITLE
Make falcor work with react-native 

### ISSUE THREAD

**Issue by mitel** [Netflix/falcor#603]
Due to `asap` dependency, building a `react-native` project will fail. 
`relay` with `react-native` has the same issue, described in details here:

https://github.com/facebook/react-native/issues/3463

**Comment by jhusain** [comment]
Technically the ASAP dependency is only used if a batch is used I believe. You can also pass in a custom scheduler to batch.

**Comment by mitel** [comment]
Just a workaround for the moment: building with webpack makes it work.
Why:
https://github.com/facebook/react-native/issues/3463#issuecomment-148792186

Small test with react-native, falcor, webpack:
https://github.com/mitel/ReactNativeFalcorStarter

**Comment by dzannotti** [comment]
@jhusain i can take this one, and see where i get if you confirm that none else is working on this (yet)

**Comment by adri** [comment]
I looked a bit into it, here are my findings. For reference here the error message:

```
Unable to resolve module domain from /Users/adri/workspace/...
/node_modules/falcor/node_modules/asap/raw.js: 
Invalid directory /Users/node_modules/domain
```

The main issue is that react natives packer require all files that are somewhere `require`d in a file, even if there are surrounded by an `if` and actually not running. I found two occurrences where this leads to a problem. 

1. [lib/index](https://github.com/Netflix/falcor/blob/master/lib/index.js#L10)
Here "promise" is required, although not necessary. The promise library requires `asap` which leads to the error message above.

2. [lib/Model.js](https://github.com/Netflix/falcor/blob/master/lib/Model.js#L9)
The ASAPScheduler requires "asap" which leads to the error message above.

Not sure how to fix it. Maybe a separate entry point for react-native?

**Comment by dzannotti** [comment]
for the time being i made a fork and changed a few things and provided an example you can find them on
https://github.com/dzannotti/falcor
https://github.com/dzannotti/react-native-falcor
I tested the above with `RN 0.14.2` `npm n3.4.1` `node 5.0.0`

The reason falcor doesn't work out of the box with react-native is indeed the use of asap (which despite only being used in the asap scheduler is declared as dep and required afterwards), the main culprit however is  https://github.com/Netflix/falcor/blob/master/lib/index.js#L7-L11 because of the use of conditional require (react native provides `Promise` implementation by default), to quote @ide "The problem here is that `require` is not just a function. It's also a pragma that tells the packager what to include. ". To release a RN compatible package i suspect that the scheduler would need to be split in smaller packages however this doesn't solve the conditional require of `Promise` which sadly has no valid resolution yet 'till RN packager either looks for a different entrypoint in `package.json` if available or implement conditional requires. 'Till then a fork is necessary

**Comment by ide** [comment]
Could falcor not include Promise? That would solve this (I think) and is the direction most libs are going -- it's the responsibility of the user of falcor to provide a compatible ES6 environment. Especially in a client-side world, not having to pay the cost of downloading + parsing unused code is modestly valuable too.

**Comment by ide** [comment]
Chatting with @dzannotti some more -- for `asap` I think we could address this with the "react-native" field in package.json (in a PR, under discussion: https://github.com/facebook/react-native/pull/2208).

The idea is that falcor could specify these top-level fields in package.json:
```json
"react-native": {
  "asap": "react-native-asap"
},
"dependencies": {
  "react-native-asap": "^1.0.0",
  // and other dependencies too, as usual
},
```

The RN packager would then know to look for react-native-asap when it finds `require('asap')` in Falcor's code. The benefits of this approach are that it addresses this issue at hand. The drawbacks are that people not using React Native would pay the cost of downloading `react-native-asap` to `node_modules` when using Falcor with Node or in a browser environment -- but importantly Webpack/Browserify would not ship `react-native-asap` to browsers and Node would not execute `react-native-asap` since it'd never get require'd.

**Comment by almasakchabayev** [comment]
What is the progress on this?

**Comment by dzannotti** [comment]
@almasakchabayev if you read my comment above there's 2 links with a working example

**Comment by almasakchabayev** [comment]
@dzannotti I have read your comments. I was just thinking that after react-native issue was resolved, falcor could work with react-native out of the box some time soon if someone is working on it.

**Comment by michaelbpaulson** [comment]
Currently no core dev on falcor is going to work on this issue for the _immediate_ future.  If this issue can / has been solved we love PRs from the community and will accept them!

**Comment by ide** [comment]
Thanks for the update @michaelbpaulson. If Netflix doesn't have an immediate need for this it sounds like this is a community need & responsibility.

The RN packager will ship with support for the "react-native" in the next 2-4 weeks (RC in 2 weeks, release in 4). The commit is already in master (https://github.com/facebook/react-native/commit/b86f14738ee8bcb925ad447e0daf58d7ee95f5bb). If someone wanted to work on this issue I think RN master might be in a place where you could work on writing a Falcor PR on top of it.

**Comment by michaelbpaulson** [comment]
@ide we do have to include promise library for now since we need to fulfill the `.then` interface. Until we have 2 options
 
* stop using .then (wont happen)
* write our own (probably wont happen) 

so we are in a difficult spot for falcor and conditional requirements.  There are browserify options to exclude certain requires, you could potentially use this to rid yourself of the promise library.  Perhaps we can have this a dist option.

**Comment by dzannotti** [comment]
@michaelbpaulson separating the asap scheduled in it's own (optional) module would be great, regarding promises, what about having a babel step to polyfill them (if needed)?

**Comment by almasakchabayev** [comment]
@ide @dzannotti Is anyone on it? I can help

**Comment by ide** [comment]
I'm not working on this.

**Comment by almasakchabayev** [comment]
@ide @dzannotti Can you guys explains what is the problem with asap library and what parts of it do not work in react-native, I will try to do something about it.

**Comment by bmamouri** [comment]
+1

**Comment by michaelbpaulson** [comment]
As previously stated.  This is an awesome feature, but its not anywhere near our road map.  We have some pretty ambitious goals over the next 6 months.  If anyone from the community would like to own this, that would be great and team falcor would be grateful.

**Comment by yorzi** [comment]
Any progress to let falcor work with ReactNative？I don't see any build errors while using falcor in a react native app, but I can not get any data based on the falcor client. Any ideas? thanks!

**Comment by clarle** [comment]
Hello!

As of #790, Falcor should support React Native out of the box, since the conditional dependencies that were being used have been removed, as well as some other issues with Babel and React Native.

For now, you can use it by installing it directly from this repository:

```js
// Inside your `package.json`, as an example
{
  "dependencies": {
    "falcor": "git@github.com:Netflix/falcor.git#f2cafdf",
    "react": "^15.0.2",
    "react-native": "^0.26.2"
  }
}
```
I've created a demo application at [clarle/falcor-react-native-demo](https://github.com/clarle/falcor-react-native-demo) that's basically the same as the Getting Started tutorial in the README here.

Feel free to keep commenting here if you run into any issues, or let me know if there's anything else I might be able to help with.  Definitely interested in seeing what people build with Falcor and React Native!

CC @yorzi @bmamouri @almasakchabayev @mitel @dzannotti @ide

**Comment by mitel** [comment]
that's very cool, thanks @clarle
