### ISSUE TITLE
undefined response after get/call

### ISSUE THREAD

**Issue by chrisvariety** [Netflix/falcor#628]
A server response that is nothing but empty atoms returns `undefined` on the promise payload. Is this expected?

An example:

```js
model.get(['studies', {from: 0, to: 1}, ['name', 'id']]).then(function (payload) {
  // payload is undefined if server returns nothing but empty atoms
});
```
[server response is empty atoms](https://gist.github.com/chrisvariety/0817aa8e001972aefbd3)

I would hope `payload` would look something like:

```
{
  json: {
    studies: { 0: null, 1: null } // or something similar, like `studies: {}`
  }
}
```

... but instead it's just null. Is this expected behavior? It makes it difficult to re-use payload handling code with different queries.

ps. Falcor is awesome, thanks for all your hard work :sparkles:

**Comment by trxcllnt** [comment]
@chrisvariety yes, this is expected when using Promises. Since Promises are required to resolve, the only option in the case of no data (which is what the server's `undefined` responses are indicating) is to resolve with `undefined`. When you use Observables (calling `subscribe` instead of `then`) instead, we can distinguish between these two cases (when data exists, onNext and onCompleted are both called, when it doesn't, only onCompleted is called).

**Comment by chrisvariety** [comment]
@trxcllnt Thanks!! I'll try `onNext` instead-- happy thanksgiving!
