### ISSUE TITLE
No error is thrown/returned when querying for a path that doesn't exist

### ISSUE THREAD

**Issue by mik01aj** [Netflix/falcor#633]
When I query some unexistent path, the backend returns `{$type: "atom"}` in this place (in the HTTP response), and this is then treated as `undefined` by the client code.

Why don't I get `{$type: "error"}`?

Why there is no error message (neither on the client side nor the server side)?

**Comment by michaelbpaulson** [comment]
@mik01aj This is called a _materialized path_.  Essentially this signals to the model that there is no data at this path so don't make another http request for it. 

To understand materialized paths lets start with how they act, then why we created them, and finally why we made them _values_ instead of errors.

```javascript
model.
    get(['path', 'that', 'doesnt', 'exsist']).
    subscribe((x) => {
        console.log('onNext', x);
    }, (e) => {
        console.log('onError', e);
    }, () => {
        console.log('onCompleted');
    });

// Will print 
onCompleted
```

What you will see is that the model will simply complete.  If promise interface is used (`.then`) then it will resolve with an undefined value.  So thats the behavior, but how is this good?  Lets imagine that we work at a company that display list of lists of movies (lolomo), say... Netflix!

```javascript
// Initial load, request a 10x10 movie grid
model.
    get(['lolomo', {to:9}, {to:9}, 'title']).
    subscribe((x) => {
        console.log('onNext', x);
    }, (e) => {
        console.log('onError', e);
    }, () => {
        console.log('onCompleted');
    });
// Lets say list 9 does not exist: Output
onNext {
    json: {
        lolomo: {
            0: {
                0: {
                    title: 'Running Man'
                }, ...
            }, ...
            8: { ... } // NO 9!!
        }
    }
}
onCompleted
```

Now lets say, which does happen, that one of these lists _does not exist_.  What should we have?  Well personally I would like falcor to _know_ it does not exist and protect me from requesting that data.  Second I would like the output to only contain the data requested.

So lets imagine what this would do to all of our code if there were errors.  Every path we would request that was outside of our bounds (usually this is always on initial load, after that you know the length of your lists and can virtualize correctly). This means on every error from falcor (through the onError channel) would have to be inspected for the _realness_(`i^2`) of error, if its a _no data_ error or a real error. This seems like a cumbersome API.  

So there you go, thats the best answer.  If you do not mind, I am going to close this issue.  If you feel like there is more to discuss please feel free to re-open and continue on (i am only closing for book keeping sake).

**Comment by mik01aj** [comment]
@michaelbpaulson Thank you very much for the detailed answer.

btw, will this great explanation also make it to the docs? :)

**Comment by mik01aj** [comment]
@michaelbpaulson could you explain how this relates to [`treatErrorsAsValues()`](https://netflix.github.io/falcor/doc/Model.html#treatErrorsAsValues)?

I suppose that in that situation "error" means "thrown exception", right?

**Comment by michaelbpaulson** [comment]
> I suppose that in that situation "error" means "thrown exception", right?
no this would be an error coming through the "onError" channel of either promise or subscribable. There can be errors of which are never thrown.  Errors from your server about some piece of data.  

```javascript
{$type: 'error', value: {unauthorized: true}}
```
You can image that the requested path you did not have authorization, so there is no need to throw that on the client side, but instead insert it into the cache and forward that through the onError channel.

As I was describing above.  What if, instead of materializing, we returned errors for missing values.  Then every error that comes through the error channel would have to be inspected for realness (then i put a joke about `i` because its unreal).  That API would be pretty hard to work with.

> @michaelbpaulson could you also explain how this relates to `treatErrorsAsValues()`?
This is orthogonal to the above question.  `treatErrorsAsValues()` is a mode where all errors, instead of going through the error channel will be put into the JSON response (except thrown errors). 

```javascript
model = new Model({
    cache: {
        foo: {
            bar: Model.atom('value'),
            baz: Model.error('ohh no!')
        }
    }
});

var request = ['foo', ['bar', 'baz']];
model.get(request).
    subscribe((x) => { 
        console.log('value', x); 
    }, (e) => { 
        console.log('error', e);  
    }, () => {
        console.log('onCompleted');
    });
model.
    treatErrorsAsValues().
    get(request).
    subscribe((x) => { 
        console.log('value TEAV', x); 
    }, (e) => { 
        console.log('error TEAV', e); 
    }, () => {
        console.log('onCompleted TEAV');
    });
```   

This would print the following.
```bash
> value { 
    foo: {
        bar: 'value'
   }
}
> error [{
    path: ['foo', 'baz'],
    value: 'ohh no!'
}]
> value TEAV { 
    foo: {
        bar: 'value',
        baz: 'ohh no!'
   }
}
> onCompleted TEAV
```

Hope that helps.
