### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by IwanKaramazow** [Netflix/falcor#655]
On my journey to 'falcorify' as much of a web app as possible, I am stuck at the point of uploading files.
Correct me if I'm wrong, but file uploading is currently not supported (no success after some experimentation).

This is merely a suggestion, but supporting file upload could have some nice use cases...
Let's say a user needs to upload a profile picture. If something like
`model.call('users.id.profile.upload', file, 'users.id.profile.src')` (upload a profile pic & get the corresponding link back) would exist, that should help developers eliminating the last REST endpoints. Apparently with graphql it's possible to upload files.

No idea if this is a good idea, has anybody thought about this?

**Comment by rnicholus** [comment]
I personally don't think that Falcor is the correct tool for uploading files. The biggest problem is that Falcor is JSON/text data. Files can certainly be application/json, but often will be binary types. In order to support file uploads in modern browsers using the File API, Falcor would have to handle `Blob` and `File` objects. I'm not a Falcor maintainer, so I may be mistaken here, but [I am quite knowledgeable with browser-based file uploading and the File API](http://fineuploader.com). It's a very complex workflow to properly support.

**Comment by steveorsomethin** [comment]
I'm currently performing issue triage as we get ready to perform a proper release, and closing/tagging as I go.

While this could be an interesting case, some of the performance characteristics implicit here mean we would be unlikely to explicitly support this. However, if you're unconcerned about perf it seems plausible that you could yourself encode your binary data as strings.
