### ISSUE TITLE
clarification on refPaths and thisPaths of a call method

### ISSUE THREAD

**Issue by almasakchabayev** [Netflix/falcor#681]
I have the following route: 
```
{
    route: 'users.create',
    call(callPath, args) {
      const user = ...
      return Observable.fromPromise(user.save()).
        map(() => [
          { 
            path: ['usersById', user.id],
          },
        ]);
    }
  }
```
I initially thought that refPaths are the paths that will be added to `['usersById', user.id]` and retrieve fields of the newly created object, however when I make the following call:
```
model.call(
      ['users', 'create'],
      [args],
      [['email'], ['id']]
    ).then(console.log)
```
1) How to use refPaths? (I have read documentation and thought it should retrieve properties of a newly created object, if it received the path)
2) how can I query for something unrelated to the newly created object, i.e. [featuredProducts, {from: 0, to: 9}, 'title'], if I want to query first page's information in the same call to the server. Does it go to 

I have read documentation multiple times and learned it by heart I think, however I am sure I misunderstanding everything about how call works... :(

**Comment by michaelbpaulson** [comment]
There are three questions here (at least as far as i can see).

1) How to use `refPaths`
2) How to use `thisPaths`
3) Preloading data
  - Returning _other_ data in a call

I'll answer them in order the best I can.  Before answering any of them I am going to first write a small example that will be applicable to _1_ & _2_.

```javascript
// Here is the router that is returning data
var router = new Router([{
    route: 'lists[{keys}].add'
    call: function(callPath, args) {
        return listService.
    
            // Use the list Id to add the new item to the list.  The item is "whatever" that is in the args.
            add(callPath[1], args).
            map((newListItem) => {
                var listRef = {
                    path: ['lists', callPath[1], newListItem.index],
                    value: ref(['items', newListItem.id])
                };
                return listRef;
            });
    }
}]);
```

#### How to use `refPaths`

So the next problem is that now that we created a new item, all we get back is the reference at the _index_ in the list.  That sucks considering we would have to make _another_ round trip to get the properties we want.  **Think again!** We can use 2 methods to get that data back.

1) We can have the call function on the server just return that extra data.  This sucks because some systems may need different parts of the new items information, so there will be some over fetching.

2)  We can use `refPaths`.  How `refPaths` work is that each _reference_ returned by the call algorithm will get the `refPaths` _concat_'d and reran through the Router's matching algorithm.  

So our model op looked like
```javascript
model.call(['lists', 123, 'add'], [...], [['name'], ['type'], ['price']]).subscribe(...);
```

This means the router would initially call the `add` function.  Once complete would attach `[['name'], ['type'], ['price']]` to each reference.  This means that the matching algorithm would match the following paths.

```javascript
call(['lists', 123, 'add']) -> [{
    path: ['lists', 123, 7],
    value: $ref(['items', 'ABC']) 
}];

//Since there were 1 or more refPaths AND 1 or more references, then produce "get" paths
// From call's resulting references.
get([
    ['items', 'ABC', 'name'],
    ['items', 'ABC', 'type'],
    ['items', 'ABC', 'price']
]) -> { ... };
```

#### thisPaths
`thisPaths` allow for another way to _post process_ a call request.  `thisPaths` will be concat'd with the following formula.

```javascript
// Which would be optimizedCallPath = ['lists', 123, 'add'] in our example
var optimizedCallPath = optimized(callPath);

// thisPath would equal ['lists', 123] in the above example
var thisPathBase = optimizedCallPath.slice(0, optimizedCallPath.length - 1);  

var fullThisPaths = thisPaths.map(x => thisPathBase.concat(x));
```

This is handy when you add something to the list and you want the length back of the list as well.  This could be done by simply having the callFunction return the length of the list as well, but much like before, it becomes a slippery slope of how much does the callFunction know about the clients and what information should it be responsible for returning.

#### Preloading data

This is probably the simplest answer to them all.  With call you can return whatever data you want!  So lets alter the above example to return the name of the item added to the list.

```javascript
// Here is the router that is returning data
var router = new Router([{
    route: 'lists[{keys}].add'
    call: function(callPath, args) {
        return listService.
    
            // Use the list Id to add the new item to the list.  The item is "whatever" that is in the args.
            add(callPath[1], args).
            map((newListItem) => {
                var listRef = {
                    path: ['lists', callPath[1], newListItem.index],
                    value: ref(['items', newListItem.id])
                };
                var listName = {
                    path: ['items', newListItem.id, 'name'],
                    value: newListItem.name
                };
                return [listName, listRef];
            });
    }
}]);
```

I hope that answers your questions @almasakchabayev and merry new year!

**Comment by michaelbpaulson** [comment]
@almasakchabayev I am going to assume that all is well.  If there are further questions, please feel free to re-open the ticket.

**Comment by boazblake** [comment]
Hi ! I am having some trouble understanding the call method as well.
Right now I am able to add data but I have to manually refresh the browser for the data to be displayed (this is retrieved by my get call that is activated on load).

I have my data stored as this:
![image](https://cloud.githubusercontent.com/assets/3834931/19622764/74492958-9877-11e6-9f0a-7c8c02349847.png)

And my server side code:
![image](https://cloud.githubusercontent.com/assets/3834931/19622759/52064844-9877-11e6-9248-85607e327d56.png)

Its a pity that the documentation is still so sparse,  I would recommend spending a little more effort in making the documentation more comprehensible , you may see a greater volume of mind-share in return.

**Comment by hgwood** [comment]
Your code looks correct to me. Your Falcor model cache on the client should be up-to-date after the `call` is done. It's up to your app to update the view accordingly. It should make a new `get` (which won't trigger a new network round trip because everything is in the cache).

That's said you could optimize further. Your `call` handler as you show it is returning the new `length` along with the contact name, but that is not required. All the `call` handler should do is require the client to invalidate the `length` like this:

```js
{ path: ['data', 'contacts', 'length'], invalidated: true }
```

This makes the minimal return payload from the `call` very small. If the clients want to get the updated length and new contact as part of the call it should request that through `refPaths` and `thisPath`.

Your code needs a few modifications to make this possible. Everything about this is documented [here](http://netflix.github.io/falcor/documentation/model.html#calling-functions). In a nutshell, you need the function to be a child of the collection (`data.contacts.add` in your case) and you need the contacts in your list to be references to another collection that is indexed by ID (this is a good idea anyway for caching, because IDs never change, while indices do).

If you need more examples than what's in the documentation, you can have a look at [this repo](https://github.com/hgwood/falcorception). Client code is [here](https://github.com/hgwood/falcorception/blob/master/client/src/node_modules/app/app.js#L37), server code is [here](https://github.com/hgwood/falcorception/blob/master/server/index.js#L104).

**Comment by boazblake** [comment]
@hgwood 
Thank you for the in-depth response, I am most likely lacking some basic conceptual understanding of Falcor. I have watched all the videos by the Falcor team and a bunch of videos by some 3rd party developers - I also came across your talk as well and will check it out later tonight. Would be cool if there was a falcor tutorial that covered both server and client side on pluralsight. I will clone your falcorception repo and see if I can dupe and understand it. Thank you again!
