### ISSUE TITLE
model returning undefined when an empty array of pathSets is returned

### ISSUE THREAD

**Issue by delaneyj** [Netflix/falcor#741]
have a situation where if i call a `localhost:1337/model.json?method=get&paths=[["foo","bar","baz",{"from":0,"to":3},["id","name"]]]` get a result of...

``` json
{
  "jsonGraph": {
    "foo": {
      "bar": {
        "baz": {
          "0": {
            "id": {
              "$type": "atom"
            },
            "name": {
              "$type": "atom"
            }
          },
          "1": {
            "id": {
              "$type": "atom"
            },
            "name": {
              "$type": "atom"
            }
          },
          "2": {
            "id": {
              "$type": "atom"
            },
            "name": {
              "$type": "atom"
            }
          },
          "3": {
            "id": {
              "$type": "atom"
            },
            "name": {
              "$type": "atom"
            }
          }
        }
      }
    }
  }
}
```

...which makes sense cause its empty.  If do the same via a `model.get('foo.bar.baz[0..3]["id","name"]')` I get an `undefined`.  I would think that I should get the same JSONGraph object, is this not the case?

**Comment by michaelbpaulson** [comment]
@delaneyj I think you may be confusing a _DataSource_ with the _Model_.  My guess is that you are using the Thenable interface (`.then`).

What essentially happens is, if a model cannot find data, we currently _materialize_ (from nothing, make something) so that our cache can know not to request the same data 2x.  Take 2 minutes to think of why we do that and it should become apparent.  But if what you request is 100% materialized, then what should we give to the user?  Well on a Subscribable (`.subscribe`), the `onNext` is _not_ called, but just `onCompleted`.  Which makes sense.  We have finished your data request and received nothing from the server.  With Thenables, there is no disambiguating between a _complete_ and a _next_ event.  There is only 2 channels, `valueAndCompleted` and `error`.  Therefore the function being invoked for a simple completion has to provide at least 0 values, and that non-value will be `undefined`.

Now, if i am completely wrong on whats happening, sorry for the explanation.

#### Post Scriptum
I noticed you are using path syntax (`'foo.bar.baz[0..3]["id","name"]'`). I would stop.  We will be removing that from the core library _soon_*.  Here is the equivalent in _Array Syntax_, `['foo', 'bar', 'baz', {to: 3} , ["id","name"]]`.  If you use path syntax you pay a performance cost of parsing the path every time, where Array Syntax is the format that falcor runs off of.   

* Soon has not been determined, but there is a PR.  It'll most likely be version `1.1.x` that this will happen.

**Comment by delaneyj** [comment]
The removal of the path syntax is fine (its actually used in a decorator that converts to a pathSet but was more concise to show).  

I am using the `then`/promise usage, the part I don't understand is why the response via http has a full jsongraph but not the DataSource.  If the materialized response has no values then something more like an array of objects with undefined values seems to make sense as that is more inline with the actual underlying jsongraph response looks like.

**Comment by trxcllnt** [comment]
@delaneyj you can configure your Model to return fully materialized responses [via the constructor](https://github.com/Netflix/falcor/blob/master/lib/Model.js#L99) or you can create a clone of an existing model that materializes by calling `var materializedModel = model._materialize();` though the team has indicated support for this method may drop in the future.

**Comment by delaneyj** [comment]
@trxcllnt anything that's not even discussed in the [API docs for Model](http://netflix.github.io/falcor/doc/Model.html) certainly scares me away from using for now.

**Comment by michaelbpaulson** [comment]
@delaneyj `_materialized()` is a private function and I don't recommend using it.  In fact, it is probable that materialize will be removed in the future.

**Comment by delaneyj** [comment]
@michaelbpaulson I figured its probably not safe to use.  I think you are right I'm complecting DataSource and Model together.  It just seems that the return (from a http call) does actually have information and value.  My reasoning is it returns an iterable structure with undefined/null values (empty $atom).  That seems much more valuable to the frontend dev than just an undefined.

**Comment by trxcllnt** [comment]
@delaneyj don't worry, materialized has been there since the beginning, and it's impossible to use the model as a DataSource without it. As you've demonstrated, it's a perfectly reasonable option to enable in certain circumstances. @michaelbpaulson hasn't always been the biggest fan because of how it adds complexity to the internal methods, but it'd be -at minimum- a breaking change, and major version rev. And the day that happens, you can count on me to revert it in a separate fork, because I need that feature too.

**Comment by michaelbpaulson** [comment]
@trxcllnt it has nothing to do with the complexity.  It was required.  But the idea of materialize is fundamentally a lie.  its putting data where no data should ever be.  We are looking into ways in which this may be better handled.  This is why I am saying that `_materialize` is dangerous.  If you are relying on the behavior of a _private_ member, its going to lead to some swirl as its inevitably going to change.

If you choose to fork over materialize, please at least, if we ever do change it of course, of which we are currently discussing, take a look at the solution before resorting to two falcors.

**Comment by steveorsomethin** [comment]
I'm currently performing issue triage as we get ready to perform a proper release, and closing/tagging as I go.

Going to close this as it sounds settled. For anyone else arriving here, I would echo the sentiment that using private members voids your warranty, but for now we are not removing _materialized.
