### ISSUE TITLE
Documentation doesn't build

### ISSUE THREAD

**Issue by cjlarose** [Netflix/falcor#742]
I've got a reproducible failure on the current head of the `gh-pages` branch (commit 50a5e500e0853fe3688203a6adbc7b4f4829cabf) using the following Dockerfile:

```
FROM node:4.3.1-onbuild
RUN apt-get update
RUN apt-get install -y rubygems ruby-dev
RUN gem install jekyll
RUN npm install -g gulp
CMD ["gulp", "serve"]
```

If I try to start this container up, I get this:

```
[07:14:29] Using gulpfile /usr/src/app/gulpfile.js
[07:14:29] Starting 'compile-less'...
[07:14:29] Starting 'js'...
[07:14:29] Finished 'js' after 656 ms
{ [Error: variable @dl-horizontal-breakpoint is undefined in file /usr/src/app/node_modules/bootstrap/less/type.less line no. 214]
  type: 'Name',
  filename: '/usr/src/app/node_modules/bootstrap/less/type.less',
  index: 4161,
  line: 214,
  callLine: NaN,
  callExtract: undefined,
  column: 21,
  extract:
   [ '',
     '  @media (min-width: @dl-horizontal-breakpoint) {',
     '    dt {' ],
  message: 'variable @dl-horizontal-breakpoint is undefined in file /usr/src/app/node_modules/bootstrap/less/type.less line no. 214',
  stack: undefined,
  lineNumber: 214,
  fileName: '/usr/src/app/node_modules/bootstrap/less/type.less',
  name: 'Error',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-less',
  __safety: { toString: [Function: bound ] } }
```

A little bit of research turns up an [issue raised on Bootstrap](https://github.com/twbs/bootstrap/issues/13948).

Modifying the `package.json` file to restrict the `bootstrap` version to exactly `3.3.5` (instead of `^3.3.5`) makes everything build just fine. This seems to be a decent short-term fix for people wanting to make small changes.

The build failure, though, seems to indicate that the `variables.less` file (or `bootstrap-variables.less` file?) in the repo was made by copying the one out of Bootstrap version 3.3.5 and modifying it for Falcor's needs. This practice seems to be very much discouraged. The long-term fix, I think, would be to do what user `orrd` suggests on the Bootstrap issue

> The solution is that rather than customizing variables.less, what you're supposed to do is still let boostrap.less include the variables.less file, and then customize your Bootstrap variables in a separate file or somewhere else that is included after boostrap.less is included, so that your variables override just the ones you want to change, but you still let it also define all of the variables in the standard variables.less.

**Comment by nicolasartman** [comment]
thanks for reporting this @cjlarose and for all the investigation. I've issued a PR that'll fix this for now by just locking the version to `3.3.5` (realistically, the Falcor site probably never needs to update bootstrap 3 unless it undergoes a complete rewrite).

Context, in case you're interested: the best/only way to set up boostrap with heavy customization some time in the past was by forking settings.less, and I think may be required by the Falcor site due to the idiosyncratic way less handles variable declarations and overriding. However, I'm planning to migrate the new site styles to the sass build of bootstrap and use a similar tactic to the one you referenced for the variable overrides, since sass seems to have simpler and more flexible includes handling.

**Comment by cjlarose** [comment]
Excellent! Thanks!

**Comment by steveorsomethin** [comment]
PR was merged. Closing. (Very late) Thanks Nicolas!
