### ISSUE TITLE
MaxRetryExceededError when a path contains a float key

### ISSUE THREAD

**Issue by ptpt** [Netflix/falcor#860]
```javascript
var F = require("falcor");
var Router = require("falcor-router");
var G = require("falcor-json-graph");
var Rx = require("rx");

const router = new Router([
        {
route: 'sequenceByKey[{ranges}].imageByKey',
get: function(pathSet) {
return Rx.Observable.create(function(observer) {
        observer.onNext({
path: ["sequenceByKey", 0, "imageByKey"],
value: G.ref(["imageByKey", "foo"]) });

        observer.onCompleted();
        });
}
},
]);

var model = new F.Model({"source": router});

const util = require('util');

function LOG(myObject) {
    console.log(util.inspect(myObject, {showHidden: false, depth: null}));
}

model.get([
        'sequenceByKey',
        {from: 0, to:1},
///// MaxRetryExceededError thrown here
        ["3333.0"],
]).subscribe(
    function(a) {
    LOG(a);
    },
    err => console.log(err),
    () => console.log("done")
    );
```

**Comment by steveorsomethin** [comment]
Possibly related to https://github.com/Netflix/falcor/issues/785.

Thanks for the report.

**Comment by benmj** [comment]
@steveorsomethin -- definitely sounds related. In #785 we saw that anything that was valid input for `parseInt` was being parsed. So `"333.0"` or even `"333.0    "` would be parsed as integer. This results in a mismatch between the string input and the integer value and seems to lead to the MaxRetryExceededError.

@ptpt -- one way to work-around the issue is to choose a prefix character that is added by your client and stripped by the server to coerce the value into string format. Something like `"|3333.0"`

**Comment by asyncanup** [comment]
i don't believe keys with `.` in them are supported with pathset array syntax (`['sequenceByKey', { from: 0, to: 1 }, ['3333.0'] ]`), because of the ambiguity with usage of `.` in route path syntax (`sequenceByKey[{ranges}].imageByKey`). maybe @lrowe or @jhusain can chime in here as well.

on a side note, i do notice that your route is for `sequenceByKey[{ranges}].imageByKey`, whereas model query path is `['sequenceByKey', { from: 0, to: 1 }, ['3333.0']]` - and they don't match. 
although, fixing that with route for `sequenceByKey[{ranges}]["3333.0"]` didn't get that route to trigger either.

**Comment by asyncanup** [comment]
@ptpt could you respond to the questions above, so we can try and address your issue?

**Comment by asyncanup** [comment]
closed until provided further details
