### ISSUE TITLE
Difference between 1.x and 2.x?

### ISSUE THREAD

**Issue by greim** [Netflix/falcor#864]
It's a bit hard for us outsiders to ascertain the state of the project. The master branch `package.json` says `0.2.0-alpha.1`, but `README.md` in that same branch mentions the `1.x` line. Meanwhile, `npm install falcor` puts `2.0.0-rc1` into my `node_modules/` folder. So I checked the `2.0.0` branch, but the readme is still talking about the `1.x` line. Admittedly, I haven't been following everything super closely, so hopefully I'm not missing something obvious. Anyhow:

 * What's the recommended version of Falcor for new projects? Presumably 2.x?
 * What changes are in the 2.x line? (I was unaware it existed until today actually.)
 * What's the roadmap from here? Even if no specific dates are mentioned. For example, is 2.x still going to be dev preview, etc?

It might also be helpful to put this info somewhere newcomers (or occasional check-in people like me) are likely to see it.

Cheers

**Comment by steveorsomethin** [comment]
Sorry about the lack of messaging about the releases and the inconsistent docs. The project is getting more attention and you've probably seen me fixing some bugs and closing issues. We'll take some time to update the ```README.md``` with a basic explanation right away, and improve on that messaging soon.

```1.x``` was a breaking change from ```0.x``` primarily due to a change to ```deref```, which you can read about [here](https://github.com/Netflix/falcor/blob/master/MIGRATIONS.md#0x-to-1x).

```2.x``` was a breaking change from ```1.x``` due to the fact that we now emit json branches leading to missing values, and (almost) always onNext, which you can read about [here](https://github.com/Netflix/falcor/blob/v2.0.0/MIGRATIONS.md).

The dual 1.x and 2.x thing is a little wonky, but we did this to give internal teams a chance to adopt the breaking changes at their leisure, since different projects depend on different versions of falcor currently. The goal was to make 2.x the current canonical version, but we wanted to let internal teams vet the release candidates before doing a full on release.

My preference is to drop the 'developer preview' qualifier at this point, but I'll defer to the rest of the team and come back with an answer.

Honestly I'm surprised the -rc versions became the default ```npm install``` version, so I'll try to figure out how to get it to default to 0.1.17 until we make an official release.

We'll try to provide a followup comment about the roadmap within a week, but in the meantime I'll be keeping a close eye on the repo and try to keep things moving. Thanks for checking in, and sorry for the confusion.

**Comment by greim** [comment]
Cool, thanks for the reply!

**Comment by sdesai** [comment]
Closing out, now that we've got 1.0.0 on npm, removed the developer preview verbiage, and MIGRATIONS.md filled out.
